create table USUARIOS (
    IDENTIFICADOR INT constraint usuarios_pk primary key,
    CONTRASEÑA varchar2(50),
    NOMBRE varchar2(20),
    APELLIDOS varchar2(40),
    DIRECCION varchar2(100),
    TELEFONO INT,
    EMAL varchar2(200),
    FOTO varchar2(4000)
);

create table GRUPOS (
    ID_GRUPO INT constraint grupos_pk primary key,
    NOMBRE varchar2(20),
    N_CONTACTOS INT
);

create table COMENTARIOS (
    CODIGO_COMENTARIO varchar2(10) constraint comentarios_pk primary key,
    TEXTO varchar2(200),
    FOTO varchar2(4000)
);

create table VEN (
    IDENTIFICADOR INT,
    CODIGO_COMENTARIO varchar2(10),
    FOREIGN KEY IDENTIFICADOR REFERENCES USUARIOS (IDENTIFICADOR)
    ON DELETE RESTRICT ON UPDATE CASCADE,
    FOREIGN KEY CODIGO_COMENTARIO REFERENCES COMENTARIOS (CODIGO_COMENTARIO)
    ON DELETE RESTRICT ON UPDATE CASCADE
);

create table VEN (
    ID_GRUPO INT,
    CODIGO_COMENTARIO varchar2(10),
    FOREIGN KEY ID_GRUPO REFERENCES GRUPOS (ID_GRUPO)
    ON DELETE RESTRICT ON UPDATE CASCADE,
    FOREIGN KEY CODIGO_COMENTARIO REFERENCES COMENTARIOS (CODIGO_COMENTARIO)
    ON DELETE RESTRICT ON UPDATE CASCADE,
);