create table `USUARIOS` (
    IDENTIFICADOR INT NOT NULL PRIMARY KEY,
    CONTRASEÑA varchar(50) NOT NULL,
    NOMBRE varchar(20),
    APELLIDOS varchar(40),
    DIRECCION varchar(100),
    TELEFONO INT,
    EMAL varchar(200),
    FOTO varchar(4000)
    );

create table GRUPOS (
    ID_GRUPO INT NOT NULL primary key,
    NOMBRE varchar(20),
    N_CONTACTOS INT
);

create table COMENTARIOS (
    CODIGO_COMENTARIO varchar(10) NOT NULL primary key,
    TEXTO varchar(200),
    FOTO varchar(4000)
);

CREATE TABLE `14`.`VEN` (
  `IDENTIFICADOR` INT NOT NULL,
  `ID_GRUPO` INT,
  `CODIGO_COMENTARIO` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`IDENTIFICADOR`),
  CONSTRAINT `ID`
    FOREIGN KEY (`IDENTIFICADOR`)
    REFERENCES `14`.`USUARIOS` (`IDENTIFICADOR`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `COD_COM`
    FOREIGN KEY (`CODIGO_COMENTARIO`)
    REFERENCES `14`.`COMENTARIOS` (`CODIGO_COMENTARIO`)
    ON DELETE NO ACTION
	ON UPDATE CASCADE,
CONSTRAINT `ID_GRUPO`
	FOREIGN KEY (`ID_GRUPO`)
    REFERENCES `14`.`GRUPOS` (`ID_GRUPO`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE);
