INSERT INTO `14`.`COMENTARIOS` (`CODIGO_COMENTARIO`, `TEXTO`, `FOTO`) VALUES ('A', 'tweet1', 'foto1');
INSERT INTO `14`.`COMENTARIOS` (`CODIGO_COMENTARIO`, `TEXTO`, `FOTO`) VALUES ('B', 'tweet2', 'foto2');
INSERT INTO `14`.`COMENTARIOS` (`CODIGO_COMENTARIO`, `TEXTO`, `FOTO`) VALUES ('C', 'tweet3', 'foto3');
INSERT INTO `14`.`COMENTARIOS` (`CODIGO_COMENTARIO`, `TEXTO`, `FOTO`) VALUES ('D', 'tweet4', 'foto4');
INSERT INTO `14`.`COMENTARIOS` (`CODIGO_COMENTARIO`, `TEXTO`, `FOTO`) VALUES ('E', 'tweet5', 'foto5');
INSERT INTO `14`.`COMENTARIOS` (`CODIGO_COMENTARIO`, `TEXTO`, `FOTO`) VALUES ('F', 'tweet6', 'foto6');
INSERT INTO `14`.`COMENTARIOS` (`CODIGO_COMENTARIO`, `TEXTO`, `FOTO`) VALUES ('G', 'tweet7', 'foto7');

INSERT INTO `14`.`GRUPOS` (`ID_GRUPO`, `NOMBRE`, `N_CONTACTOS`) VALUES ('1', 'Juan', '12');
INSERT INTO `14`.`GRUPOS` (`ID_GRUPO`, `NOMBRE`, `N_CONTACTOS`) VALUES ('2', 'Jordi', '16');
INSERT INTO `14`.`GRUPOS` (`ID_GRUPO`, `NOMBRE`, `N_CONTACTOS`) VALUES ('3', 'Jesus', '23');
INSERT INTO `14`.`GRUPOS` (`ID_GRUPO`, `NOMBRE`, `N_CONTACTOS`) VALUES ('4', 'Albert', '73');
INSERT INTO `14`.`GRUPOS` (`ID_GRUPO`, `NOMBRE`, `N_CONTACTOS`) VALUES ('5', 'Pau', '34');
INSERT INTO `14`.`GRUPOS` (`ID_GRUPO`, `NOMBRE`, `N_CONTACTOS`) VALUES ('6', 'Miquel Angel', '84');

INSERT INTO `14`.`USUARIOS` (`IDENTIFICADOR`, `CONTRASEÑA`, `NOMBRE`, `APELLIDOS`, `DIRECCION`, `TELEFONO`, `EMAL`) VALUES ('1', '123A@', 'Juan', 'Hernandez', 'Reus', '654213566', 'Jhernandez@gmail.com');
INSERT INTO `14`.`USUARIOS` (`IDENTIFICADOR`, `CONTRASEÑA`, `NOMBRE`, `APELLIDOS`, `DIRECCION`, `TELEFONO`, `EMAL`) VALUES ('2', '412p*', 'Jesus', 'Garcia', 'Barcelona', '653216549', 'JGarcia@hotmail.com');
INSERT INTO `14`.`USUARIOS` (`IDENTIFICADOR`, `CONTRASEÑA`, `NOMBRE`, `APELLIDOS`, `DIRECCION`, `TELEFONO`, `EMAL`) VALUES ('3', 'a-_-2', 'Albert', 'Plaza', 'Tarragona', '564321549', 'APlaza@gmail.com');
INSERT INTO `14`.`USUARIOS` (`IDENTIFICADOR`, `CONTRASEÑA`, `NOMBRE`, `APELLIDOS`, `DIRECCION`, `TELEFONO`, `EMAL`) VALUES ('4', '5Y-/-_2', 'Miquel Angel', 'Montero', 'Lleida', '487562356', 'mmontero@gmail.com');
INSERT INTO `14`.`USUARIOS` (`IDENTIFICADOR`, `CONTRASEÑA`, `NOMBRE`, `APELLIDOS`, `DIRECCION`, `TELEFONO`, `EMAL`) VALUES ('5', '1234', 'Pau', 'Martinez', 'Montblanc', '698756321', 'pmartinez@hotmail.com');
INSERT INTO `14`.`USUARIOS` (`IDENTIFICADOR`, `CONTRASEÑA`, `NOMBRE`, `APELLIDOS`, `DIRECCION`, `TELEFONO`, `EMAL`) VALUES ('6', 'Ggh6&', 'Hector', 'Jimenez', 'Girona', '159875632', 'hjimenez32@gmail.com');
